In [651]:
import pandas as pd
import numpy as np
import re

In [653]:
energy = pd.read_excel('Lesson_3_hometask_data/Energy Indicators.xls', header = 17,
                                                skipfooter = 38)

In [655]:
energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'], inplace=True)

In [657]:
energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

In [659]:
energy['Energy Supply'] = energy['Energy Supply'] * 1_000_000

In [661]:
energy.replace(to_replace=r'\.{2,}', value=np.NaN, regex=True, inplace=True)
pd.set_option('display.float_format', '{:,.0f}'.format)

In [663]:
country_rename_dict = {
    "Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"
}

energy['Country'] = energy['Country'].replace(country_rename_dict)

In [665]:
energy['Country'] = energy['Country'].apply(lambda x: re.sub(r'\(.*\)', '', x))  
energy['Country'] = energy['Country'].apply(lambda x: re.sub(r'\d+', '', x))

In [667]:
pd.set_option('display.max_rows', None)

energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,"321,000,000",10,79
1,Albania,"102,000,000",35,100
2,Algeria,"1,959,000,000",51,1
3,American Samoa,NaN,NaN,1
4,Andorra,"9,000,000",121,89
5,Angola,"642,000,000",27,71
6,Anguilla,"2,000,000",136,0
7,Antigua and Barbuda,"8,000,000",84,0
8,Argentina,"3,378,000,000",79,24
9,Armenia,"143,000,000",48,28
10,Aruba,"12,000,000",120,15
11,Australia,"5,386,000,000",231,12
12,Austria,"1,391,000,000",164,72
13,Azerbaijan,"567,000,000",60,6
14,Bahamas,"45,000,000",118,0
15,Bahrain,"574,000,000",425,0
16,Bangladesh,"1,625,000,000",10,2
17,Barbados,"19,000,000",69,0
18,Belarus,"1,142,000,000",120,0
19,Belgium,"2,338,000,000",210,10
20,Belize,"13,000,000",39,65
21,Benin,"170,000,000",16,0
22,Bermuda,"6,000,000",88,0
23,Bhutan,"63,000,000",83,100
24,Bolivia,"336,000,000",32,31
25,"Bonaire, Sint Eustatius and Saba","5,000,000",213,0
26,Bosnia and Herzegovina,"266,000,000",70,41
27,Botswana,"86,000,000",39,0
28,Brazil,"12,149,000,000",59,70
29,British Virgin Islands,"2,000,000",85,0
30,Brunei Darussalam,"127,000,000",310,0
31,Bulgaria,"703,000,000",97,17
32,Burkina Faso,"164,000,000",10,15
33,Burundi,"58,000,000",6,87
34,Cabo Verde,"7,000,000",15,21
35,Cambodia,"250,000,000",17,57
36,Cameroon,"307,000,000",14,71
37,Canada,"10,431,000,000",296,62
38,Cayman Islands,"8,000,000",131,0
39,Central African Republic,"23,000,000",5,86
40,Chad,"77,000,000",6,0
41,Chile,"1,613,000,000",92,28
42,China,"127,191,000,000",93,20
43,"China, Hong Kong Special Administrative Region","585,000,000",82,0
44,"China, Macao Special Administrative Region","47,000,000",83,0
45,Colombia,"1,513,000,000",32,63
46,Comoros,"5,000,000",7,12
47,Congo,"102,000,000",23,58
48,Cook Islands,"1,000,000",48,0
49,Costa Rica,"222,000,000",47,89
50,Côte d'Ivoire,"547,000,000",25,23
51,Croatia,"321,000,000",75,64
52,Cuba,"585,000,000",51,1
53,Curaçao,"78,000,000",502,0
54,Cyprus,"82,000,000",71,6
55,Czech Republic,"1,751,000,000",166,7
56,Democratic People's Republic of Korea,"612,000,000",25,70
57,Democratic Republic of the Congo,"888,000,000",12,100
58,Denmark,"725,000,000",129,34
59,Djibouti,"11,000,000",13,0
60,Dominica,"2,000,000",28,37
61,Dominican Republic,"339,000,000",33,11
62,Ecuador,"680,000,000",43,48
63,Egypt,"3,422,000,000",39,9
64,El Salvador,"176,000,000",29,56
65,Equatorial Guinea,"73,000,000",91,6
66,Eritrea,"34,000,000",7,1
67,Estonia,"258,000,000",195,4
68,Ethiopia,"1,394,000,000",15,100
69,Faeroe Islands,"9,000,000",179,39
70,Falkland Islands,"1,000,000",258,33
71,Fiji,"31,000,000",36,62
72,Finland,"1,374,000,000",252,20
73,France,"10,597,000,000",166,17
74,French Guiana,"13,000,000",52,62
75,French Polynesia,"12,000,000",44,27
76,Gabon,"99,000,000",60,38
77,Gambia,"14,000,000",7,0
78,Georgia,"163,000,000",40,82
79,Germany,"13,261,000,000",165,18
80,Ghana,"316,000,000",12,63
81,Gibraltar,"8,000,000",245,0
82,Greece,"993,000,000",90,25
83,Greenland,"9,000,000",166,78
84,Grenada,"5,000,000",43,0
85,Guadeloupe,"33,000,000",70,15
86,Guam,NaN,NaN,0
87,Guatemala,"452,000,000",29,50
88,Guernsey,0,6,0
89,Guinea,"145,000,000",12,48
90,Guinea-Bissau,"29,000,000",17,0
91,Guyana,"34,000,000",45,0
92,Haiti,"172,000,000",16,13
93,Honduras,"217,000,000",28,38
94,Hungary,"947,000,000",95,3
95,Iceland,"312,000,000",957,100
96,India,"33,195,000,000",26,15
97,Indonesia,"8,754,000,000",35,12
98,Iran,"9,172,000,000",119,6
99,Iraq,"2,077,000,000",61,8
100,Ireland,"548,000,000",117,21
101,Isle of Man,0,4,1
102,Israel,"997,000,000",128,1
103,Italy,"6,530,000,000",109,34
104,Jamaica,"108,000,000",39,6
105,Japan,"18,984,000,000",149,10
106,Jersey,"3,000,000",34,0
107,Jordan,"325,000,000",45,0
108,Kazakhstan,"3,548,000,000",208,8
109,Kenya,"873,000,000",20,74
110,Kiribati,"1,000,000",8,0
111,Kuwait,"1,475,000,000",410,0
112,Kyrgyzstan,"167,000,000",29,93
113,Lao People's Democratic Republic,"85,000,000",13,93
114,Latvia,"183,000,000",91,49
115,Lebanon,"289,000,000",55,7
116,Lesotho,"48,000,000",23,100
117,Liberia,"83,000,000",19,0
118,Libya,"707,000,000",113,0
119,Liechtenstein,"3,000,000",79,96
120,Lithuania,"282,000,000",95,41
121,Luxembourg,"168,000,000",307,46
122,Madagascar,"166,000,000",7,51
123,Malawi,"101,000,000",6,89
124,Malaysia,"3,417,000,000",116,8
125,Maldives,"15,000,000",43,0
126,Mali,"66,000,000",4,65
127,Malta,"31,000,000",75,1
128,Marshall Islands,"1,000,000",28,0
129,Martinique,"33,000,000",84,3
130,Mauritania,"51,000,000",13,0
131,Mauritius,"58,000,000",46,4
132,Mexico,"7,944,000,000",64,13
133,Micronesia,"2,000,000",21,3
134,Mongolia,"475,000,000",166,0
135,Montenegro,"42,000,000",67,66
136,Montserrat,"1,000,000",153,0
137,Morocco,"796,000,000",23,16
138,Mozambique,"469,000,000",18,95
139,Myanmar,"682,000,000",13,72
140,Namibia,"63,000,000",27,96
141,Nauru,"1,000,000",60,0
142,Nepal,"458,000,000",16,100
143,Netherlands,"3,199,000,000",190,6
144,New Caledonia,"51,000,000",200,20
145,New Zealand,"876,000,000",196,73
146,Nicaragua,"149,000,000",25,41
147,Niger,"87,000,000",5,0
148,Nigeria,"5,589,000,000",32,18
149,Niue,0,65,0
150,Northern Mariana Islands,NaN,NaN,0
151,Norway,"1,388,000,000",273,98
152,Oman,"1,015,000,000",260,0
153,Pakistan,"2,868,000,000",16,32
154,Palau,"3,000,000",152,19
155,Panama,"158,000,000",42,58
156,Papua New Guinea,"144,000,000",20,24
157,Paraguay,"228,000,000",35,100
158,Peru,"858,000,000",28,52
159,Philippines,"1,781,000,000",18,26
160,Poland,"4,121,000,000",107,6
161,Portugal,"899,000,000",86,53
162,Puerto Rico,"56,000,000",15,1
163,Qatar,"1,396,000,000",664,0
164,South Korea,"11,007,000,000",221,2
165,Republic of Moldova,"93,000,000",23,5
166,Réunion,"59,000,000",70,28
167,Romania,"1,339,000,000",68,34
168,Russian Federation,"30,709,000,000",214,17
169,Rwanda,"95,000,000",9,36
170,Saint Helena,0,40,9
171,Saint Kitts and Nevis,"4,000,000",73,0
172,Saint Lucia,"6,000,000",33,0
173,Saint Pierre and Miquelon,"1,000,000",162,2
174,Saint Vincent and the Grenadines,"3,000,000",28,17
175,Samoa,"4,000,000",22,31
176,Sao Tome and Principe,"3,000,000",14,10
177,Saudi Arabia,"7,985,000,000",264,0
178,Senegal,"154,000,000",11,2
179,Serbia,"618,000,000",69,27
180,Seychelles,"9,000,000",94,2
181,Sierra Leone,"67,000,000",11,64
182,Singapore,"1,120,000,000",207,0
183,Sint Maarten,"12,000,000",327,0
184,Slovakia,"711,000,000",131,20
185,Slovenia,"287,000,000",139,32
186,Solomon Islands,"6,000,000",11,0
187,Somalia,"126,000,000",12,0
188,South Africa,"6,341,000,000",119,2
189,South Sudan,"28,000,000",2,0
190,Spain,"4,923,000,000",106,38
191,Sri Lanka,"388,000,000",19,60
192,State of Palestine,"61,000,000",14,0
193,Sudan,"608,000,000",16,78
194,Suriname,"34,000,000",65,22
195,Swaziland,"49,000,000",39,41
196,Sweden,"2,044,000,000",212,47
197,Switzerland,"1,113,000,000",136,58
198,Syrian Arab Republic,"542,000,000",28,12
199,Tajikistan,"106,000,000",13,100
200,Thailand,"5,336,000,000",79,4
201,The former Yugoslav Republic of Macedonia,"117,000,000",56,26
202,Timor-Leste,"7,000,000",6,0
203,Togo,"134,000,000",19,80
204,Tonga,"3,000,000",28,0
205,Trinidad and Tobago,"824,000,000",611,0
206,Tunisia,"430,000,000",39,3
207,Turkey,"4,897,000,000",64,29
208,Turkmenistan,"1,102,000,000",210,0
209,Turks and Caicos Islands,"3,000,000",85,0
210,Tuvalu,NaN,NaN,0
211,Uganda,"452,000,000",12,68
212,Ukraine,"4,844,000,000",107,8
213,United Arab Emirates,"2,710,000,000",300,0
214,United Kingdom of Great Britain and Northern I...,"7,920,000,000",124,11
215,United Republic of Tanzania,"994,000,000",20,31
216,United States of America,"90,838,000,000",286,12
217,United States Virgin Islands,NaN,NaN,0
218,Uruguay,"196,000,000",58,72
219,Uzbekistan,"1,798,000,000",62,21
220,Vanuatu,"3,000,000",10,15
221,Venezuela,"2,871,000,000",95,68
222,Viet Nam,"2,554,000,000",28,45
223,Wallis and Futuna Islands,0,26,0
224,Yemen,"344,000,000",13,0
225,Zambia,"400,000,000",26,100
226,Zimbabwe,"480,000,000",32,53

In [669]:
GDP = pd.read_csv('Lesson_3_hometask_data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_76261.csv', header = 2)

In [671]:
country_rename_dict = {
    "Korea, Rep.": "South Korea",
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
}

GDP['Country Name'] = GDP['Country Name'].replace(country_rename_dict)

In [673]:
GDP

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,962,907,263","2,983,635,196","3,092,429,050","3,276,184,358","3,395,798,883","2,481,857,123","2,929,446,578","3,279,343,544","3,648,573,136",NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,"24,210,632,546","24,963,977,551","27,078,797,299","31,775,749,181","30,285,794,057","33,813,171,214",...,"898,277,807,343","828,942,805,458","972,998,927,354","1,012,306,000,425","1,009,721,174,055","933,391,782,090","1,085,745,178,851","1,191,423,176,243","1,245,472,471,676",NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"19,134,221,645","18,116,572,395","18,753,456,498","18,053,222,687","18,799,444,490","19,955,929,052","14,259,995,441","14,497,243,872","17,233,051,620",NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,"11,904,954,210","12,707,877,772","13,630,758,805","14,469,094,144","15,803,761,887","16,921,087,955",...,"771,766,914,345","694,360,980,069","687,849,196,676","770,494,988,149","826,483,769,985","789,801,651,563","849,312,422,223","883,973,910,899","799,105,950,274",NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"90,496,420,507","52,761,617,226","73,690,154,991","79,450,688,259","70,897,962,732","48,501,561,204","66,505,129,988","104,399,746,853","84,824,654,482",NaN
5,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"11,386,853,113","11,861,199,831","13,019,726,212","15,379,509,892","15,585,105,131","15,241,458,745","18,032,010,564","19,017,242,586","23,547,179,830",NaN
6,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,789,881,259","2,896,610,480","3,000,162,081","3,218,419,897","3,155,149,348","2,891,001,149","3,324,647,529","3,380,612,573","3,785,067,332",NaN
7,Arab World,ARB,GDP (current US$),NY.GDP.MKTP.CD,NaN,"19,997,084,154","20,327,670,692","22,362,957,618","24,811,627,082","26,769,289,694",...,"2,544,700,996,741","2,500,823,407,238","2,572,203,993,724","2,867,348,492,604","2,899,029,698,317","2,562,783,626,988","2,969,239,218,342","3,609,805,711,776","3,512,421,040,998",NaN
8,United Arab Emirates,ARE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"370,275,469,560","369,255,326,236","390,516,804,017","427,049,432,149","417,989,721,734","349,473,015,337","415,178,792,770","502,731,935,197","514,130,432,653",NaN
9,Argentina,ARG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,"24,450,604,878","18,272,123,664","25,605,249,382","28,344,705,967",...,"594,749,285,413","557,532,320,663","643,628,393,281","524,819,892,360","447,754,683,615","385,740,508,437","486,564,085,480","632,790,070,063","646,075,277,525",NaN
10,Armenia,ARM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"10,553,337,518","10,546,136,236","11,527,458,709","12,457,940,695","13,619,290,539","12,641,698,583","13,878,908,629","19,513,506,553","24,085,749,592",NaN
11,American Samoa,ASM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"673,000,000","671,000,000","612,000,000","639,000,000","647,000,000","721,000,000","750,000,000","871,000,000",NaN,NaN
12,Antigua and Barbuda,ATG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,437,755,556","1,489,692,593","1,531,151,852","1,661,529,630","1,725,351,852","1,410,796,296","1,601,366,667","1,867,733,333","2,033,085,185",NaN
13,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,"18,607,682,977","19,684,003,149","19,923,683,188","21,540,963,447","23,801,123,808","25,977,284,156",...,"1,351,296,372,254","1,206,836,962,282","1,325,582,658,157","1,427,809,041,019","1,392,723,834,563","1,328,414,058,378","1,556,735,770,437","1,690,858,246,994","1,728,057,316,696",NaN
14,Austria,AUT,GDP (current US$),NY.GDP.MKTP.CD,"6,624,086,313","7,346,566,038","7,793,042,529","8,414,050,621","9,213,648,656","10,041,659,445",...,"379,546,097,301","393,687,359,770","414,926,138,133","452,582,294,973","442,983,642,372","434,397,601,558","480,467,037,339","471,773,629,830","511,685,203,845",NaN
15,Azerbaijan,AZE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"53,076,235,355","37,866,996,883","40,866,627,352","47,112,470,052","48,174,235,294","42,693,000,000","54,825,411,765","78,807,470,588","72,356,176,471",NaN
16,Burundi,BDI,GDP (current US$),NY.GDP.MKTP.CD,"195,999,990","202,999,992","213,500,006","232,749,998","260,750,008","158,994,963",...,"3,104,003,546","2,644,487,777","2,723,586,963","2,667,182,200","2,576,518,880","2,649,680,261","2,775,798,697","3,338,722,828","2,642,161,669",NaN
17,Belgium,BEL,GDP (current US$),NY.GDP.MKTP.CD,"11,810,619,368","12,561,701,694","13,436,827,167","14,445,805,381","16,168,044,450","17,597,783,297",...,"461,044,767,545","474,271,566,740","500,908,767,352","542,638,913,428","536,726,344,405","529,694,473,502","598,494,036,474","593,438,820,508","644,782,756,683",NaN
18,Benin,BEN,GDP (current US$),NY.GDP.MKTP.CD,"226,195,578","235,668,221","236,434,954","253,927,697","269,819,006","289,908,680",...,"11,388,160,997","11,821,065,852","12,701,655,846","14,262,408,080","14,391,686,309","15,651,545,209","17,690,083,520","17,401,746,309","19,676,049,076",NaN
19,Burkina Faso,BFA,GDP (current US$),NY.GDP.MKTP.CD,"330,442,816","350,247,234","379,567,099","394,040,667","410,321,645","422,916,790",...,"11,832,159,316","12,833,363,045","14,106,955,615","15,890,066,221","16,032,813,503","17,725,010,533","19,697,516,284","18,820,218,691","20,324,617,845",NaN
20,Bangladesh,BGD,GDP (current US$),NY.GDP.MKTP.CD,"4,274,894,083","4,817,580,375","5,081,413,542","5,319,458,562","5,386,054,833","5,906,636,792",...,"195,146,608,978","265,224,515,675","293,732,446,625","321,362,752,442","351,231,654,604","373,979,442,362","416,271,647,911","460,131,688,909","437,415,331,041",NaN
21,Bulgaria,BGR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"50,811,995,689","53,964,253,212","59,309,748,166","66,289,266,349","68,631,726,289","70,716,821,235","84,417,951,261","90,642,851,836","102,407,653,021",NaN
22,Bahrain,BHR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"32,523,297,872","33,884,680,851","37,204,813,830","39,567,978,723","40,446,808,511","35,837,632,979","40,840,212,766","46,680,398,936","46,079,867,021",NaN
23,"Bahamas, The",BHS,GDP (current US$),NY.GDP.MKTP.CD,"169,735,994","190,021,993","212,169,992","237,649,991","266,559,990","300,271,989",...,"11,671,900,000","11,745,100,000","12,236,700,000","12,615,800,000","13,016,200,000","9,958,200,000","11,368,900,000","13,136,400,000","14,338,500,000",NaN
24,Bosnia and Herzegovina,BIH,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"16,404,348,871","17,116,926,328","18,326,373,366","20,484,053,869","20,482,608,755","20,226,036,564","23,672,712,242","24,534,663,636","27,514,782,476",NaN
25,Belarus,BLR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"56,454,889,147","47,723,545,321","54,725,302,250","60,031,173,808","64,410,122,847","61,371,755,326","69,673,747,132","73,775,179,925","71,857,382,746",NaN
26,Belize,BLZ,GDP (current US$),NY.GDP.MKTP.CD,"28,072,478","29,965,000","31,857,592","33,750,114","36,194,586","40,110,040",...,"2,193,050,000","2,240,200,000","2,266,300,000","2,293,250,000","2,388,300,000","2,042,850,000","2,420,550,000","2,846,700,000","3,066,850,000",NaN
27,Bermuda,BMU,GDP (current US$),NY.GDP.MKTP.CD,"72,400,000","76,500,000","80,700,000","82,600,000","92,200,000","98,000,000",...,"6,654,541,000","6,899,911,000","7,142,316,000","7,225,977,000","7,423,465,000","6,887,147,000","7,286,607,000","7,827,980,000","8,141,700,000",NaN
28,Bolivia,BOL,GDP (current US$),NY.GDP.MKTP.CD,"373,250,000","406,000,000","443,916,667","478,000,000","538,583,333","598,333,333",...,"33,000,198,248","33,941,126,200","37,508,642,165","40,287,647,930","40,895,322,844","36,629,843,805","40,406,111,695","44,008,282,878","45,135,398,009",NaN
29,Brazil,BRA,GDP (current US$),NY.GDP.MKTP.CD,"17,030,465,539","17,275,940,449","19,231,747,852","23,287,712,878","20,963,733,695","22,465,522,884",...,"1,802,212,206,905","1,795,693,482,653","2,063,514,977,334","1,916,933,898,038","1,873,288,205,186","1,476,107,231,194","1,670,647,399,035","1,951,923,942,083","2,173,665,655,937",NaN
30,Barbados,BRB,GDP (current US$),NY.GDP.MKTP.CD,"80,021,847","85,363,759","88,782,583","99,893,761","99,252,731","105,021,997",...,"5,288,057,750","5,330,761,500","5,517,340,450","5,629,916,200","5,788,288,000","5,168,344,450","5,275,242,050","6,257,303,500","6,720,733,200",NaN
31,Brunei Darussalam,BRN,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,"114,039,501",...,"12,930,296,852","11,400,266,055","12,128,168,047","13,566,908,401","13,469,235,348","12,005,799,664","14,006,496,614","16,681,536,443","15,128,292,981",NaN
32,Bhutan,BTN,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,187,815,804","2,357,504,761","2,591,358,010","2,583,335,721","2,735,683,570","2,457,604,334","2,768,802,960","2,898,227,743",NaN,NaN
33,Botswana,BWA,GDP (current US$),NY.GDP.MKTP.CD,"30,411,414","32,902,613","35,644,957","38,091,843","41,616,348","45,788,696",...,"13,530,748,845","15,082,637,184","16,105,155,857","17,031,943,186","16,725,908,149","14,960,291,106","18,750,946,600","20,321,958,850","19,396,084,498",NaN
34,Central African Republic,CAF,GDP (current US$),NY.GDP.MKTP.CD,"112,155,598","123,134,583","124,482,774","129,379,124","142,025,079","150,574,795",...,"1,695,825,714","1,825,018,145","2,072,349,973","2,220,979,146","2,221,301,351","2,326,720,900","2,516,498,412","2,382,618,615","2,555,492,085",NaN
35,Canada,CAN,GDP (current US$),NY.GDP.MKTP.CD,"40,563,768,947","41,038,192,838","42,336,211,556","45,140,337,827","49,503,663,836","54,649,410,479",...,"1,556,508,816,217","1,527,994,741,907","1,649,265,644,244","1,725,329,192,783","1,743,725,183,673","1,655,684,730,000","2,007,472,181,464","2,161,483,369,422","2,142,470,914,401",NaN
36,Central Europe and the Baltics,CEB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,297,123,697,169","1,321,226,675,267","1,467,424,389,928","1,657,633,874,969","1,685,123,570,509","1,678,756,939,340","1,926,804,401,016","1,955,925,827,814","2,267,760,561,102",NaN
37,Switzerland,CHE,GDP (current US$),NY.GDP.MKTP.CD,"10,412,232,621","11,713,348,834","12,989,649,694","14,283,872,299","15,833,133,858","16,780,226,225",...,"694,118,186,380","687,895,460,903","695,200,833,086","725,568,717,468","721,369,112,727","741,999,406,006","813,408,787,222","818,426,550,206","884,940,402,230",NaN
38,Channel Islands,CHI,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"10,109,968,847","9,169,278,193","9,170,079,926","10,026,153,345","10,032,440,928","9,439,810,776","11,157,002,973","11,308,300,346","12,507,927,144",NaN
39,Chile,CHL,GDP (current US$),NY.GDP.MKTP.CD,"4,110,000,000","4,829,238,095","5,631,285,444","5,591,307,028","5,964,195,925","6,108,679,126",...,"242,450,355,828","249,344,863,933","276,154,259,987","295,857,562,992","278,285,058,719","254,042,159,309","315,515,014,839","302,116,539,409","335,533,331,669",NaN
40,China,CHN,GDP (current US$),NY.GDP.MKTP.CD,"59,716,249,311","50,056,685,957","47,209,186,415","50,706,614,526","59,708,125,204","70,436,008,642",...,"11,061,572,618,579","11,233,313,730,349","12,310,491,333,981","13,894,907,857,881","14,279,968,506,272","14,687,744,162,801","17,820,459,508,852","17,881,782,683,707","17,794,783,039,552",NaN
41,Cote d'Ivoire,CIV,GDP (current US$),NY.GDP.MKTP.CD,"546,203,559","618,245,634","645,284,474","761,047,198","921,063,327","919,771,229",...,"45,815,005,169","48,407,761,037","52,512,343,997","58,522,477,787","60,382,894,697","63,027,852,805","72,794,636,654","70,173,140,101","78,875,489,245",NaN
42,Cameroon,CMR,GDP (current US$),NY.GDP.MKTP.CD,"614,206,068","652,777,608","694,247,864","718,320,845","776,650,177","814,083,266",...,"32,210,233,020","33,814,337,044","36,098,547,033","39,955,552,190","39,667,757,528","40,773,241,177","45,011,937,347","44,347,206,073","49,279,410,983",NaN
43,"Congo, Dem. Rep.",COD,GDP (current US$),NY.GDP.MKTP.CD,"3,359,404,118","3,086,746,857","3,779,841,429","6,213,185,743","2,881,545,273","4,043,901,818",...,"37,917,706,497","37,134,801,555","38,019,264,795","47,568,210,010","51,775,829,877","48,716,961,860","55,328,482,784","65,801,547,620","66,383,287,003",NaN
44,"Congo, Rep.",COG,GDP (current US$),NY.GDP.MKTP.CD,"131,731,863","151,675,739","166,521,240","172,233,431","185,693,725","198,318,064",...,"12,434,793,867","10,931,328,151","11,834,473,039","14,773,900,289","13,976,637,780","11,468,687,464","14,825,690,211","15,817,030,155","15,321,055,823",NaN
45,Colombia,COL,GDP (current US$),NY.GDP.MKTP.CD,"4,031,152,977","4,540,447,761","4,955,538,219","4,836,166,667","5,973,366,667","5,760,761,905",...,"293,492,370,193","282,720,100,286","311,866,875,157","334,198,218,098","323,031,701,193","270,348,342,541","318,524,633,225","345,329,875,079","363,493,841,244",NaN
46,Comoros,COM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"966,029,601","1,012,835,493","1,077,439,757","1,188,797,449","1,195,019,532","1,225,039,197","1,296,089,480","1,242,519,408","1,352,380,971",NaN
47,Cabo Verde,CPV,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,749,857,620","1,849,789,993","1,996,741,545","2,205,099,509","2,252,177,134","1,821,565,618","2,051,842,610","2,247,003,348","2,533,819,406",NaN
48,Costa Rica,CRI,GDP (current US$),NY.GDP.MKTP.CD,"507,513,830","490,325,182","479,180,824","511,902,137","542,578,367","592,981,162",...,"56,441,920,821","58,847,019,610","60,516,044,657","62,420,164,992","64,417,670,521","62,395,610,760","64,960,725,734","69,243,626,029","86,497,941,439",NaN
49,Caribbean small states,CSS,GDP (current US$),NY.GDP.MKTP.CD,"641,146,359","699,601,326","750,604,795","782,562,092","849,473,872","941,356,066",...,"35,085,992,997","33,933,421,225","35,438,120,141","36,727,457,620","38,046,955,434","31,763,210,393","37,091,445,808","48,740,490,013","53,296,161,046",NaN
50,Cuba,CUB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"87,132,800,000","91,370,407,864","96,850,649,692","100,050,036,096","103,427,600,000","107,351,800,000",NaN,NaN,NaN,NaN
51,Curacao,CUW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"3,058,779,218","3,024,690,168","3,033,433,240","3,046,364,804","3,026,124,134","2,534,327,598","2,739,608,156","3,075,180,835","3,281,419,347",NaN
52,Cayman Islands,CYM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"4,708,167,233","4,909,322,237","5,166,281,305","5,530,178,441","5,941,896,608","5,655,358,021","6,060,026,520","6,600,843,963","7,139,428,558",NaN
53,Cyprus,CYP,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"19,909,278,417","21,046,462,281","22,946,570,629","25,754,001,368","26,196,667,100","25,555,093,854","30,372,874,320","30,976,176,887","33,886,930,712",NaN
54,Czechia,CZE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"189,107,698,562","198,160,659,304","221,563,575,696","251,992,360,762","256,794,209,029","251,109,660,603","290,972,714,482","301,831,228,326","343,207,874,554",NaN
55,Germany,DEU,GDP (current US$),NY.GDP.MKTP.CD,"84,619,845,881","96,558,204,043","105,895,435,234","112,232,503,744","123,330,404,665","134,774,688,191",...,"3,423,568,450,957","3,537,784,107,981","3,763,092,263,753","4,052,008,447,224","3,957,208,055,216","3,940,142,541,354","4,348,297,440,388","4,163,596,357,879","4,525,703,903,628",NaN
56,Djibouti,DJI,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,424,391,785","2,604,955,229","2,762,581,334","2,913,466,732","3,088,853,639","3,185,150,981","3,385,825,229","3,674,298,479","4,098,530,514",NaN
57,Dominica,DMA,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"540,737,037","576,229,630","521,551,852","554,770,370","611,537,037","504,214,815","555,266,667","607,159,259","653,992,593",NaN
58,Denmark,DNK,GDP (current US$),NY.GDP.MKTP.CD,"6,361,166,545","7,058,361,229","7,953,274,741","8,466,044,980","9,677,401,337","10,870,670,865",...,"301,758,922,338","312,181,849,372","331,610,593,962","355,293,374,912","345,401,473,013","355,631,021,932","408,378,204,640","401,945,576,108","407,091,920,305",NaN
59,Dominican Republic,DOM,GDP (current US$),NY.GDP.MKTP.CD,"672,399,700","654,100,200","824,100,000","940,799,900","1,025,599,900","888,100,000",...,"71,164,826,837","75,704,647,878","79,998,046,306","85,555,390,139","88,941,372,558","78,844,656,298","94,243,425,938","113,537,368,176","121,444,279,314",NaN
60,Algeria,DZA,GDP (current US$),NY.GDP.MKTP.CD,"2,723,615,451","2,434,747,056","2,001,444,544","2,702,982,018","2,909,316,435","3,136,284,307",...,"187,493,855,609","180,763,839,522","189,880,896,903","194,554,483,656","193,459,662,091","164,873,415,325","186,231,205,262","225,638,456,572","247,626,161,016",NaN
61,East Asia & Pacific (excluding high income),EAP,GDP (current US$),NY.GDP.MKTP.CD,"80,752,362,534","71,139,478,707","64,884,938,432","70,180,391,291","81,068,677,593","94,462,962,774",...,"13,329,363,887,708","13,621,109,083,386","14,888,272,499,557","16,648,930,593,615","17,222,812,070,663","17,496,305,186,280","20,849,863,760,042","21,124,945,071,215","21,162,836,277,192",NaN
62,Early-demographic dividend,EAR,GDP (current US$),NY.GDP.MKTP.CD,"151,408,515,299","161,302,482,593","165,738,639,753","175,832,421,253","201,669,284,249","218,788,604,348",...,"10,246,602,222,996","10,547,190,614,053","11,448,641,742,933","11,610,507,701,899","11,834,959,859,720","11,006,437,195,990","12,811,302,058,069","14,147,623,772,392","14,945,896,099,125",NaN
63,East Asia & Pacific,EAS,GDP (current US$),NY.GDP.MKTP.CD,"157,146,103,914","158,406,594,385","162,133,212,500","180,953,395,656","207,763,121,785","231,255,277,193",...,"22,000,917,165,876","22,781,793,863,032","24,334,957,894,980","26,494,505,143,187","27,040,135,154,758","27,163,485,040,464","31,155,716,955,057","30,673,443,320,596","30,780,176,881,541",NaN
64,Europe & Central Asia (excluding high income),ECA,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,509,288,407,450","1,448,928,141,200","1,494,523,919,240","1,468,176,944,856","1,498,314,054,530","1,437,142,037,121","1,670,340,541,089","1,817,978,495,945","2,129,704,371,516",NaN
65,Europe & Central Asia,ECS,GDP (current US$),NY.GDP.MKTP.CD,"426,424,801,995","469,110,075,856","513,039,887,673","561,049,368,761","620,035,842,390","676,117,339,710",...,"20,583,236,057,318","20,511,321,020,006","21,765,864,936,204","23,306,311,175,509","23,031,892,537,933","22,286,624,242,751","25,523,993,209,132","25,662,572,829,777","27,554,069,781,140",NaN
66,Ecuador,ECU,GDP (current US$),NY.GDP.MKTP.CD,"2,069,464,937","1,753,850,955","1,518,207,703","1,824,343,871","2,244,146,103","2,387,047,396",...,"97,209,558,000","97,671,433,000","104,467,486,000","107,478,962,000","107,595,829,000","95,865,472,000","107,435,101,000","116,586,079,000","118,844,826,000",NaN
67,"Egypt, Arab Rep.",EGY,GDP (current US$),NY.GDP.MKTP.CD,"4,206,270,175","4,494,575,422","4,035,461,922","4,187,146,119","4,709,245,635","4,948,667,540",...,"329,366,576,819","332,441,717,791","248,362,771,739","262,588,632,527","318,678,815,490","383,817,841,547","424,671,765,456","476,747,720,365","396,002,496,997",NaN
68,Euro area,EMU,GDP (current US$),NY.GDP.MKTP.CD,"251,413,246,920","279,722,204,489","309,382,572,882","340,512,613,271","377,249,606,355","412,364,260,985",...,"11,828,599,572,765","12,124,585,812,207","12,839,881,576,234","13,867,949,267,318","13,587,020,300,289","13,266,857,904,728","14,917,737,268,178","14,452,048,668,851","15,780,686,672,317",NaN
69,Eritrea,ERI,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [675]:
ScimEn = pd.read_excel('Lesson_3_hometask_data/scimagojr country rank 1996-2023.xlsx')

In [677]:
GDP = GDP[['Country Name'] + [str(year) for year in range(2006, 2016)]]
ScimEn_top15 = scimEn[scimEn['Rank'] <= 15]
merged = pd.merge(energy, scimEn_top15, left_on='Country', right_on='Country', how='inner')
final_merged = pd.merge(merged, GDP, left_on='Country', right_on='Country Name', how='inner')

In [679]:
final_merged.set_index('Country', inplace=True)
columns_to_keep = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 
                   'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', 
                   '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
final_merged = final_merged[columns_to_keep]

In [681]:
def answer_one():
    return final_merged

In [683]:
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Australia,14,27993,27254,608021,84747,22,234,"5,386,000,000",231,12,"748,417,562,770","855,007,458,585","1,056,112,427,190","928,762,122,698","1,148,838,233,481","1,398,610,616,773","1,547,532,281,116","1,577,123,329,411","1,468,265,356,428","1,351,296,372,254"
Brazil,15,27316,26888,307607,71778,11,154,"12,149,000,000",59,70,"1,107,626,541,711","1,397,114,486,471","1,695,855,083,552","1,666,996,438,681","2,208,837,745,214","2,616,156,223,977","2,465,227,803,012","2,472,819,535,743","2,456,043,727,199","1,802,212,206,905"
Canada,8,41209,40390,915491,142691,22,284,"10,431,000,000",296,62,"1,319,264,809,591","1,468,820,407,783","1,552,989,690,722","1,374,625,142,157","1,617,343,367,486","1,793,326,630,175","1,828,366,481,522","1,846,597,421,835","1,805,749,878,440","1,556,508,816,217"
China,1,402188,400158,5077232,3511673,13,343,"127,191,000,000",93,20,"2,752,118,657,184","3,550,327,802,998","4,594,336,785,738","5,101,691,124,285","6,087,191,746,679","7,551,545,703,441","8,532,185,381,681","9,570,471,111,832","10,475,624,944,355","11,061,572,618,579"
France,12,30810,30139,547122,89958,18,221,"10,597,000,000",166,17,"2,317,861,544,691","2,655,816,911,867","2,926,802,941,586","2,700,075,882,519","2,646,230,027,988","2,870,408,553,990","2,683,007,095,787","2,816,077,607,875","2,861,236,112,552","2,442,483,452,642"
Germany,6,50906,49773,777362,160302,15,252,"13,261,000,000",165,18,"3,046,308,753,671","3,484,056,680,855","3,808,786,022,312","3,479,800,820,863","3,468,154,343,000","3,824,828,563,521","3,597,896,500,945","3,808,086,291,482","3,965,800,686,310","3,423,568,450,957"
India,3,81853,79757,968523,369256,12,237,"33,195,000,000",26,15,"940,259,888,788","1,216,736,438,835","1,198,895,139,006","1,341,888,016,995","1,675,615,519,485","1,823,051,829,895","1,827,637,590,410","1,856,721,507,622","2,039,126,479,155","2,103,588,360,045"
Italy,9,38700,36909,639473,147302,17,209,"6,530,000,000",109,34,"1,958,563,654,386","2,222,524,108,128","2,417,508,414,187","2,209,484,319,013","2,144,936,254,535","2,306,974,020,278","2,097,929,495,122","2,153,225,581,941","2,173,255,507,986","1,845,428,048,839"
Japan,4,58342,57735,717946,154848,12,228,"18,984,000,000",149,10,"4,601,663,122,650","4,579,750,920,355","5,106,679,115,127","5,289,493,117,994","5,759,071,769,013","6,233,147,172,341","6,272,362,996,105","5,212,328,181,166","4,896,994,405,353","4,444,930,651,964"
South Korea,10,38362,38046,618762,105419,16,198,"11,007,000,000",221,2,"1,053,216,909,888","1,172,614,086,540","1,047,339,010,225","943,941,876,219","1,143,672,241,150","1,253,289,537,501","1,278,046,536,287","1,370,632,955,321","1,484,488,526,272","1,466,038,936,206"
Russian Federation,7,46186,45868,217996,96688,5,112,"30,709,000,000",214,17,"989,932,071,353","1,299,703,478,482","1,660,848,058,303","1,222,645,900,056","1,524,916,715,224","2,045,922,753,398","2,208,293,553,878","2,292,470,078,346","2,059,241,589,895","1,363,482,182,198"
Spain,13,29840,29156,614087,104845,21,216,"4,923,000,000",106,38,"1,261,846,683,275","1,476,746,276,855","1,636,115,447,612","1,496,587,590,848","1,427,989,078,917","1,487,568,659,241","1,330,994,811,670","1,362,186,923,158","1,380,244,561,362","1,206,164,777,553"

In [685]:
def answer_two():
    Top15 = answer_one()
    gdp_columns = [str(year) for year in range(2006, 2016)]
    avgGDP = Top15[gdp_columns].mean(axis=1, skipna=True)

    return avgGDP.sort_values(ascending=False)

In [687]:
answer_two()

Country
China                6,927,706,587,677
Japan                5,239,642,145,207
Germany              3,590,728,711,392
France               2,692,000,013,150
Italy                2,152,982,940,441
Brazil               1,988,888,979,247
Russian Federation   1,666,745,638,113
Canada               1,616,359,264,593
India                1,602,352,077,023
Spain                1,406,644,481,049
South Korea          1,221,328,061,561
Australia            1,207,996,576,071
dtype: float64

In [689]:
def answer_three():
    Top15 = answer_one()
    gdp_columns = [str(year) for year in range(2006, 2016)]
    avgGDP = Top15[gdp_columns].mean(axis=1, skipna=True)
    country = avgGDP.sort_values(ascending=False).index[5]
    
    gdp_2006 = Top15.loc[country, '2006']
    gdp_2015 = Top15.loc[country, '2015']
    
    gdp_change = gdp_2015 - gdp_2006
    
    return gdp_change

In [691]:
answer_three()

694585665193.94

In [693]:
def answer_four():
    Top15 = answer_one()
    Top15['Self-Citations to Total Citations Ratio'] = Top15['Self-citations'] / Top15['Citations']
    max_ratio = Top15['Self-Citations to Total Citations Ratio'].max()
    country_with_max_ratio = Top15['Self-Citations to Total Citations Ratio'].idxmax()
    
    return (country_with_max_ratio, max_ratio)

In [695]:
answer_four()

('China', 0.6916510807463594)

In [697]:
def answer_five():
    Top15 = answer_one()
    Top15['Estimated Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    sorted_top15 = Top15.sort_values('Estimated Population', ascending=False)
    
    return sorted_top15.index[2]

In [699]:
answer_five()

'Brazil'

In [701]:
def answer_six():
    Top15 = answer_one()
    Top15['Citable Documents per Capita'] = Top15['Citable documents'] / Top15['Energy Supply per Capita']
    correlation = Top15['Citable Documents per Capita'].corr(Top15['Energy Supply per Capita'])
    
    return correlation

In [703]:
answer_six()

-0.5597137144873789

In [705]:
def answer_seven():
    Top15 = answer_one()
    ContinentDict = {'China':'Asia', 
                     'United States':'North America', 
                     'Japan':'Asia', 
                     'United Kingdom':'Europe', 
                     'Russian Federation':'Europe', 
                     'Canada':'North America', 
                     'Germany':'Europe', 
                     'India':'Asia',
                     'France':'Europe', 
                     'South Korea':'Asia', 
                     'Italy':'Europe', 
                     'Spain':'Europe', 
                     'Iran':'Asia',
                     'Australia':'Australia', 
                     'Brazil':'South America'}
    Top15['Continent'] = Top15.index.map(ContinentDict)
    Top15['Estimated Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    continent_stats = Top15.groupby('Continent')['Estimated Population'].agg(
        size='size',
        sum='sum',
        mean='mean',
        std='std'
    )
    
    return continent_stats

In [707]:
answer_seven()

               size           sum        mean         std
Continent
Asia              4 2,821,590,756 705,397,689 713,877,879
Australia         1    23,316,017  23,316,017         NaN
Europe            5   394,058,699  78,811,740  38,132,276
North America     1    35,239,865  35,239,865         NaN
South America     1   205,915,254 205,915,254         NaN